### PR TITLE
[Hitalo] Continue Evoluindo - With love from Rio de Janeiro, Brazil

### PR DESCRIPTION
**Pull request by HitaloM**

### CODE REVIEW

**Review by zjunior06 — COMMENTED** [review]
You never used Evolution X, how you want keep your memory here? Ah, and you need evolve too. Kbye

**Comment by ruizlenato** [comment]
> You never used Evolution X, how you want keep your memory here? Ah, and you need evolve too. Kbye

Tru lmao

**Comment by nienkjapa** [comment]
I don't come here to defend anyone, when Hitalo needs to be criticized I speak in the face.

I just don't understand how just a PixelExperience maintainer can have such an arrogance to criticize other people for liking such a custom rom.

I myself criticize EvolutionX, Hitalo and several other people, but there is no reason to keep making this a racket. Also, if you are going to keep saying things and then post them in open or closed Telegram groups, this is totally ridiculous.

Renatoh even criticizes so much and sent a pull request. When are you going to stop fighting over useless things?

I have been called a child by both, now I see who the real children are here.

Who leave their work to criticize. One with an S9, the other with G5 Plus. instead of developing something, they are criticizing useless bullshit.
sucks

**Comment by nienkjapa** [comment]
Ah, I'm not going to argue about it anymore. You can make brief comments there, they will just be a waste of time.

I only protect who is correct. But when it's wrong, I also stab myself in the back.

**Comment by Mijotchi** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL

**Comment by HitaloKun** [comment]
@RealAkito I closed that PR, just to explain to you, intention was no general discussion in this repo, something unnecessary, but, I just wanted to say that those people know nothing about me and about the roms I use and especially this Renatoh has an S9 without root and does not use custom roms, just GSIs at most and port rom, that ZJRDroid is a Pixel Experience user and he hates EvoX.

Again sorry for these guys who polluted the repository.

**Pull request closed without merging**
