### PR TITLE
Love from Palembang, Indonesia

### PR DESCRIPTION
**Pull request by Tantriudz**

### CODE REVIEW

**Comment by hugwalk** [comment]
@Tantriudz I LOVE YOU ROBBY

**Comment by RealAkito** [comment]
- *Cough* No homo here

**Comment by RealAkito** [comment]
uh

**Comment by Tantriudz** [comment]
sorry for closing lol, thought i have double requested.

**Comment by Tantriudz** [comment]
thanks everyone! love u guys. no homo tho.

**Comment by RealAkito** [comment]
@Tantriudz Alright

**Pull request merged**
